// Coucou plugin for DeepSeek Harness — generated by Coucou.
// Display events are fire-and-forget. Approval and questions wait for a click
// in the island, and hand the request to the Web GUI (next()) if Coucou is
// closed or nobody clicks. Nothing here allows a tool without that click.

import net from "node:net";
import module from "node:module";
import { pathToFileURL } from "node:url";

export const name = "coucou";

const AGENT = "dsh";
const CONNECT_MS = 400;
const DECISION_MS = 110_000;
/** Shortest gap between two streaming preview lines: the island repaints on each. */
const STREAM_MS = 350;
/** Shortest gap between two context-usage readings: it moves slowly. */
const USAGE_MS = 5_000;

function textOf(content) {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content
    .filter((block) => block && (block.type === "text" || block.type === undefined) && typeof block.text === "string")
    .map((block) => block.text)
    .join("\n");
}

function sessionIdOf(agent) {
  const id = agent?.id ?? agent?.session?.id ?? agent?.session?.header?.id ?? "";
  return typeof id === "string" ? id : String(id ?? "");
}

/** The one line an unknown error is worth. Never the whole stack: the island shows one line. */
function errorText(error) {
  if (typeof error === "string") return error;
  const message = error?.message ?? error?.reason;
  if (typeof message === "string" && message.trim()) return message.trim();
  return "Agent error";
}

/** A model-request failure, as the loop reports it before it retries or gives up. */
function failureText(failure) {
  if (typeof failure === "string") return failure;
  const message = failure?.message ?? failure?.reason ?? failure?.kind;
  if (typeof message === "string" && message.trim()) return message.trim();
  return "Request failed";
}

/** One line, short enough for the island's ticker row. */
function toOneLine(text) {
  if (typeof text !== "string") return "";
  return text.replace(/\s+/g, " ").trim().slice(0, 120);
}

function lastSegment(path) {
  if (typeof path !== "string") return "";
  const cleaned = path.replace(/[\\/]+$/, "");
  const idx = Math.max(cleaned.lastIndexOf("\\"), cleaned.lastIndexOf("/"));
  return idx >= 0 ? cleaned.slice(idx + 1) : cleaned;
}

function findCreateUserMessage() {
  const keys = Object.keys(module._cache ?? {});
  const hit = keys.find((key) => key.replaceAll("\\", "/").includes("/@deepseek-ai/dsh-llm/"));
  if (!hit) return null;
  return import(pathToFileURL(hit).href)
    .then((mod) => mod.createUserMessage ?? null)
    .catch(() => null);
}

let createUserMessagePromise;

function userMessage(text) {
  if (!createUserMessagePromise) createUserMessagePromise = findCreateUserMessage();
  return createUserMessagePromise.then((create) => {
    if (typeof create === "function") {
      return create({
        content: [{ type: "text", text }],
        source: { kind: "user" },
      });
    }
    return {
      role: "user",
      id: `coucou-${Date.now()}`,
      content: [{ type: "text", text }],
      source: { kind: "user" },
    };
  });
}

function talk(pipe, payload, waitMs) {
  return new Promise((resolve) => {
    if (!pipe) {
      resolve(null);
      return;
    }
    let settled = false;
    const done = (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(value);
    };
    const socket = net.connect(pipe);
    let buf = "";
    const timer = setTimeout(() => {
      socket.destroy();
      done(null);
    }, waitMs);
    socket.on("connect", () => {
      socket.write(`${JSON.stringify(payload)}\n`);
      if (waitMs <= CONNECT_MS) {
        socket.end();
        done(null);
      }
    });
    socket.on("data", (chunk) => {
      buf += chunk.toString("utf8");
      const nl = buf.indexOf("\n");
      if (nl >= 0) {
        const line = buf.slice(0, nl).trim();
        socket.end();
        done(line);
      }
    });
    socket.on("error", () => done(null));
    socket.on("end", () => {
      if (waitMs > CONNECT_MS && !settled) done(buf.trim() || null);
    });
  });
}

function display(pipe, payload) {
  void talk(pipe, payload, CONNECT_MS);
}

export function apply(ctx, config) {
  const pipe = typeof config?.pipe === "string" ? config.pipe : "";
  const steerPipe = typeof config?.steerPipe === "string" ? config.steerPipe : "";
  const calls = new Map();
  const lastAssistant = new Map();
  /** Sessions whose turn is open: a Stop edge is still owed for them. */
  const turnOpen = new Set();
  /** The agent of each live session, so a session event finds its own agent. */
  const agentsBySession = new Map();
  /** Last time each session's usage was read, so a slow gauge is not re-read. */
  const usageState = new Map();
  /** Sessions that have run a tool since their turn opened. */
  const sawWork = new Set();
  /** Reads a session's context pressure; null until `ctx.inject` has run. */
  let readPressure = null;
  let current = null;
  const remember = (agent) => {
    if (!agent || agent.origin === "subagent") return;
    current = agent;
  };

  ctx.on("agent/created", ({ agent }) => {
    remember(agent);
    const sid = sessionIdOf(agent);
    agentsBySession.set(sid, agent);
    display(pipe, {
      hook_event_name: "SessionStart",
      session_id: sid,
      coucou_agent: AGENT,
      cwd: agent?.session?.header?.cwd ?? agent?.cwd ?? "",
    });
  });

  ctx.on("agent/disposed", ({ agent }) => {
    const sid = sessionIdOf(agent);
    agentsBySession.delete(sid);
    usageState.delete(sid);
    sawWork.delete(sid);
    if (current && sessionIdOf(current) === sid) current = null;
    display(pipe, {
      hook_event_name: "SessionEnd",
      session_id: sid,
      coucou_agent: AGENT,
    });
  });

  // The session store's own edges. `agent/*` already covers the pill, but a
  // session can be restored from the store, or dropped for publication
  // rollback, without an agent ever being created or disposed — and then
  // nothing announced its folder.
  ctx.on("session/created", (session) => {
    const sid = session?.id ?? "";
    if (!sid) return;
    const cwd = session?.header?.cwd ?? "";
    display(pipe, {
      hook_event_name: "SessionStart",
      session_id: String(sid),
      coucou_agent: AGENT,
      cwd,
    });
  });

  ctx.on("session/disposed", (session) => {
    const sid = session?.id ?? "";
    if (!sid) return;
    display(pipe, {
      hook_event_name: "SessionEnd",
      session_id: String(sid),
      coucou_agent: AGENT,
    });
  });

  // A file was read or found absent. DSH already reports the tool call itself;
  // this is the only signal for a read the model made outside a visible tool
  // step, and it stays a plain ticker line: nothing here changes a state.
  ctx.on("fs/observed", (target, observation) => {
    const path = target?.path ?? target?.targetKey ?? "";
    if (!path) return;
    const missing = observation?.kind === "absent";
    display(pipe, {
      hook_event_name: "Warning",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: missing ? `⚠ missing · ${lastSegment(path)}` : `Reads · ${lastSegment(path)}`,
    });
  });

  // A session was archived and its running work is being stopped: the turn
  // will not finish on its own, so the pill must not sit on "working" for ever.
  ctx.on("workspace/session-stop", (request) => {
    const sid = request?.sessionId ? String(request.sessionId) : "";
    if (!sid) return;
    turnOpen.delete(sid);
    sawWork.delete(sid);
    display(pipe, {
      hook_event_name: "Stop",
      session_id: sid,
      coucou_agent: AGENT,
      last_assistant_message: lastAssistant.get(sid) ?? "",
    });
  });


  // Context usage. Optional on purpose: `tokenMeter` and `sessionProjections`
  // are separate plugins, and a profile that does not load them must keep
  // working exactly as before — `ctx.inject` simply never runs the body then.
  const reportUsage = (agent) => {
    if (!agent || typeof readPressure !== "function") return;
    const sid = sessionIdOf(agent);
    const now = Date.now();
    if (now - (usageState.get(sid) ?? 0) < USAGE_MS) return;
    usageState.set(sid, now);
    let reading;
    try {
      reading = readPressure(agent);
    } catch {
      return;
    }
    if (!reading || !reading.tokens) return;
    display(pipe, {
      hook_event_name: "ContextUsage",
      session_id: sid,
      coucou_agent: AGENT,
      used_tokens: reading.tokens,
      context_window: reading.window ?? 0,
    });
  };

  try {
    ctx.inject(["tokenMeter", "sessionProjections"], (meterCtx) => {
      readPressure = (agent) => {
        const session = agent?.session;
        if (!session) return null;
        const pressure = meterCtx.sessionProjections.stateOf(session, "contextPressure");
        // The projection is the cheap read and usually has what we need; the
        // full measure() replays the surface, so it is only a fallback.
        if (pressure?.pressureTokens) {
          return { tokens: pressure.pressureTokens, window: pressure.contextWindow ?? 0 };
        }
        const measured = meterCtx.tokenMeter.measure(session);
        return { tokens: measured?.totalTokens ?? 0, window: pressure?.contextWindow ?? 0 };
      };
    });
  } catch {
    // No meter in this profile: the island simply has no usage pill.
  }

  // Background jobs and scheduled reminders, sent as they change. Both services
  // are optional the same way the meter is: a profile that does not load them
  // keeps working, it just has nothing to report.
  const sendJobs = (jobsService, sessionId) => {
    if (!sessionId) return;
    let jobs;
    try {
      jobs = jobsService.list(sessionId);
    } catch {
      return;
    }
    const all = jobs ?? [];
    const live = all.filter((job) => job.status === "running" || job.status === "stopping");
    const last = all.find((job) => job.status === "failed") ?? all[all.length - 1];
    display(pipe, {
      hook_event_name: "JobsChanged",
      session_id: sessionId,
      coucou_agent: AGENT,
      jobs_running: live.length,
      jobs_total: all.length,
      // Only the producer's own label and progress line: never a job's output.
      jobs_label: last ? `${last.status} · ${last.label}` : "",
      jobs_progress: live[0]?.progress ?? "",
    });
  };

  try {
    ctx.inject(["jobs"], (jobsCtx) => {
      // One subscription for the whole process, filtered by owner on the way
      // out: `{ owners: 'all' }` is the only filter that needs no session.
      try {
        const off = jobsCtx.jobs.events.subscribe({ owners: "all" }, (event) => {
          const owner = event?.job?.owner ?? event?.owner;
          if (owner) sendJobs(jobsCtx.jobs, owner);
        });
        if (typeof off === "function") ctx.effect(() => off);
      } catch {
        // No event stream: the snapshot on each status change still lands.
      }
      ctx.on("agent/created", ({ agent }) => sendJobs(jobsCtx.jobs, sessionIdOf(agent)));
      ctx.on("agent/status", ({ agent }) => sendJobs(jobsCtx.jobs, sessionIdOf(agent)));
    });
  } catch {
    // No job registry in this profile.
  }

  try {
    ctx.inject(["schedule"], (scheduleCtx) => {
      const sendSchedule = async () => {
        let entries;
        try {
          entries = await scheduleCtx.schedule.catalog();
        } catch {
          return;
        }
        const all = entries ?? [];
        const active = all.filter((entry) => entry.status === "active");
        const next = active
          .map((entry) => entry.scheduledAt)
          .filter((at) => typeof at === "string")
          .sort()[0] ?? "";
        display(pipe, {
          hook_event_name: "ScheduleChanged",
          session_id: sessionIdOf(current),
          coucou_agent: AGENT,
          reminders_active: active.length,
          reminders_total: all.length,
          reminders_next: next,
        });
      };
      ctx.on("schedule/changed", () => void sendSchedule());
    });
  } catch {
    // No schedule service in this profile.
  }

  // Permission presets management: report effective preset and allow switching via reverse pipe.
  let presetsService = null;
  const sendPreset = (session) => {
    if (!presetsService || !session) return;
    try {
      const currentPreset = presetsService.current(session);
      const names = presetsService.names ?? [];
      display(pipe, {
        hook_event_name: "PresetChanged",
        session_id: sessionIdOf(session),
        coucou_agent: AGENT,
        preset: currentPreset,
        presets: names,
      });
    } catch {}
  };

  try {
    ctx.inject(["permissionPresets"], (permCtx) => {
      presetsService = permCtx.permissionPresets;
      ctx.on("agent/created", ({ agent }) => {
        if (agent?.session) sendPreset(agent.session);
      });
      ctx.on("session/event", (session, event) => {
        if (event?.type === "permission/preset") {
          sendPreset(session);
        }
      });
    });
  } catch {
    // Permission presets not installed in this profile.
  }

  ctx.on("agent/pre-step", (payload, next) => {
    remember(payload?.agent);
    const sid = sessionIdOf(payload?.agent);
    turnOpen.add(sid);
    // Only a prompt the human actually sent is a UserPromptSubmit. DSH puts its
    // own injected context in this same batch — a background job finishing
    // (`tool-jobs`, form `notice`), a changed approval policy (`user-approval`) —
    // and those are user-role messages too. The island reads UserPromptSubmit as
    // "the turn that asked is over", so a notice landing just after a permission
    // request or a question cancelled the card on screen and handed the request
    // back to DSH's own UI, which left the session waiting on it.
    const text = (payload?.messages ?? [])
      .filter((message) => message?.source?.kind === "user")
      .map((message) => textOf(message?.content))
      .filter(Boolean)
      .join("\n");
    if (text.trim()) {
      display(pipe, {
        hook_event_name: "UserPromptSubmit",
        session_id: sid,
        coucou_agent: AGENT,
        prompt: text,
      });
    }
    return next();
  });

  ctx.on("session/event", (session, event) => {
    if (event?.type !== "assistant/message") return;
    const sid = session?.id ?? sessionIdOf(session);
    const text = textOf(event.data?.message?.content ?? event.data?.content);
    if (text.trim()) lastAssistant.set(sid, text);
    // The meter is per session: report for this session's own agent, not
    // whichever one happened to be remembered last.
    reportUsage(agentsBySession.get(sid) ?? current);
  });

  // The answer as it is being written. Throttled: the island repaints on every
  // event, and a token-by-token feed would be thousands of them. The line is
  // short (the island shows one row) and is only ever a preview — the whole
  // answer comes with Stop.
  const streamState = new Map();
  ctx.on("agent/assistant-stream", ({ agent, frame }) => {
    const sid = sessionIdOf(agent);
    if (frame?.type === "start") {
      streamState.set(sid, { text: "", lastSent: 0 });
      return;
    }
    if (frame?.type === "end") {
      streamState.delete(sid);
      return;
    }
    if (frame?.type !== "chunk") return;
    const state = streamState.get(sid) ?? { text: "", lastSent: 0 };
    streamState.set(sid, state);
    const chunk = frame.chunk;
    if (chunk?.type === "text-delta" && typeof chunk.text === "string") {
      state.text += chunk.text;
    } else {
      return;
    }
    const now = Date.now();
    if (now - state.lastSent < STREAM_MS) return;
    state.lastSent = now;
    const line = state.text.replace(/\s+/g, " ").trim().slice(-120);
    if (!line) return;
    display(pipe, {
      hook_event_name: "StreamingText",
      session_id: sid,
      coucou_agent: AGENT,
      message: line,
    });
  });

  ctx.on("tools/pre-execute", (exec, next) => {
    const callId = exec?.callId ? String(exec.callId) : "";
    if (callId) calls.set(callId, { name: exec.name, arguments: exec.arguments ?? {} });
    sawWork.add(sessionIdOf(exec?.agent));
    display(pipe, {
      hook_event_name: "PreToolUse",
      session_id: sessionIdOf(exec?.agent),
      coucou_agent: AGENT,
      tool_name: exec?.name ?? "",
      tool_input: exec?.arguments ?? {},
    });
    // Display only. Never deny or ask from this path.
    return next();
  });

  ctx.on("tools/post-execute", (exec, result, next) => {
    const cached = calls.get(String(exec?.callId ?? ""));
    const failed = result?.isError === true;
    display(pipe, {
      // A failed tool is its own canonical event: the relay drops `tool_response`
      // (it can be a whole file), so sending PostToolUse with a flag never
      // reached the island and a failed tool looked like a successful one.
      hook_event_name: failed ? "PostToolUseFailure" : "PostToolUse",
      session_id: sessionIdOf(exec?.agent),
      coucou_agent: AGENT,
      tool_name: exec?.name ?? "",
      tool_input: cached?.arguments ?? exec?.arguments ?? {},
    });
    return next();
  });

  // Observe the frozen, lossless-JSON final outcome of every tool call.
  // Provides a concise result status or error detail without leaking large payload.
  ctx.on("tools/result", (exec, result) => {
    if (!result) return;
    if (result.isError) {
      const errStr = errorText(result.error);
      if (errStr && errStr !== "Agent error") {
        display(pipe, {
          hook_event_name: "Warning",
          session_id: sessionIdOf(exec?.agent),
          coucou_agent: AGENT,
          message: `⚠ ${exec?.name ?? "tool"}: ${errStr}`,
        });
      }
    }
  });

  ctx.on("agent/turn-stopping", (payload) => {
    const sid = sessionIdOf(payload?.agent);
    turnOpen.delete(sid);
    sawWork.delete(sid);
    const text = lastAssistant.get(sid) ?? "";
    display(pipe, {
      hook_event_name: "Stop",
      session_id: sid,
      coucou_agent: AGENT,
      last_assistant_message: text,
    });
  });

  // The turn errored, terminally. Without this the island stayed on "working"
  // for ever: the island has had an error state since day one, nothing fed it.
  ctx.on("agent/error", (payload) => {
    const sid = sessionIdOf(payload?.agent);
    turnOpen.delete(sid);
    sawWork.delete(sid);
    display(pipe, {
      hook_event_name: "StopFailure",
      session_id: sid,
      coucou_agent: AGENT,
      message: errorText(payload?.error),
    });
  });

  // One failed model request. The loop may still retry it (dsh-llm-retry owns
  // that decision), so this is a ticker line and never the red state: a red
  // Mochi for a request that succeeded on the second try would be a lie.
  ctx.on("agent/request-error", (payload, next) => {
    display(pipe, {
      hook_event_name: "Warning",
      session_id: sessionIdOf(payload?.agent),
      coucou_agent: AGENT,
      message: `⚠ ${failureText(payload?.failure)}`,
    });
    return next();
  });

  // The driver went idle without a turn-stopping edge (a cancellation, a crash
  // in a tool's own await). The pill would otherwise never leave "working".
  // Only for a turn that actually did something: a pre-step the loop rejected
  // (plan mode does this) opens and closes a "turn" that never ran, and a
  // finished card for it would be noise.
  ctx.on("agent/status", ({ agent, status }) => {
    if (status !== "idle") return;
    const sid = sessionIdOf(agent);
    if (!turnOpen.has(sid)) return;
    turnOpen.delete(sid);
    if (!sawWork.has(sid)) return;
    sawWork.delete(sid);
    display(pipe, {
      hook_event_name: "Stop",
      session_id: sid,
      coucou_agent: AGENT,
      last_assistant_message: lastAssistant.get(sid) ?? "",
    });
  });

  // Context compaction failed: the session carries on, but its context is now
  // bigger than it should be. A line, not an error state.
  ctx.on("compaction/summary-error", (payload) => {
    display(pipe, {
      hook_event_name: "Warning",
      session_id: sessionIdOf(payload?.session ?? current),
      coucou_agent: AGENT,
      message: `⚠ compaction failed: ${errorText(payload?.error)}`,
    });
  });

  // The DeepSeek sign-in is gone: every further request will fail until the
  // user signs in again, so this one is worth the red state.
  ctx.on("deepseek-account/session-expired", () => {
    display(pipe, {
      hook_event_name: "StopFailure",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: "DeepSeek sign-in expired",
    });
  });

  // A workflow run: the phase titles and narration lines become ticker steps,
  // so a long multi-agent run reads as progress instead of one silent wait.
  // The child agents inside it report on their own; this is the script's frame.
  ctx.on("workflow/start", (info) => {
    const name = info?.meta?.name ?? "workflow";
    display(pipe, {
      hook_event_name: "SubagentStart",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: `▶ ${name}`,
    });
  });

  ctx.on("workflow/phase", (info, title) => {
    if (!title) return;
    display(pipe, {
      hook_event_name: "SubagentStart",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: `▸ ${title}`,
    });
  });

  ctx.on("workflow/log", (info, message) => {
    const line = toOneLine(message);
    if (!line) return;
    display(pipe, {
      hook_event_name: "SubagentStart",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: line,
    });
  });

  ctx.on("workflow/end", (info, result) => {
    const name = info?.meta?.name ?? "workflow";
    const done = result?.stopReason === "completed";
    display(pipe, {
      hook_event_name: "SubagentStop",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: done
        ? `✔ ${name} · ${result?.agentsStarted ?? 0} agents`
        : `✗ ${name}: ${result?.error ?? result?.stopReason ?? "failed"}`,
    });
  });

  ctx.on("subagent/start", (info) => {
    display(pipe, {
      hook_event_name: "SubagentStart",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: info?.provider ? `+ ${info.provider}` : "+ subagent",
    });
  });

  ctx.on("subagent/end", (info) => {
    display(pipe, {
      hook_event_name: "SubagentStop",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: "• subagent done",
    });
    const text = textOf(info?.lastAssistantMessage);
    if (text.trim() && info?.id) lastAssistant.set(String(info.id), text);
  });

  ctx.on("approval/request", async (req, next) => {
    const callId = req?.callId ? String(req.callId) : "";
    const cached = callId ? calls.get(callId) : undefined;
    const tool = req?.toolName || cached?.name || "tool";
    const input = cached?.arguments ?? {};
    const line = await talk(pipe, {
      hook_event_name: "PermissionRequest",
      session_id: sessionIdOf(req?.agent ?? current),
      coucou_agent: AGENT,
      tool_name: tool,
      tool_input: input,
      request_id: callId || `dsh-${Date.now()}`,
    }, DECISION_MS);
    if (line === "allow") return "allowed-once";
    if (line === "deny") return "rejected";
    return next();
  });

  ctx.on("user-questions/request", async (req, next) => {
    const questions = Array.isArray(req?.questions) ? req.questions : [];
    if (questions.length === 0) return next();
    const requestId = `dsh-q-${Date.now()}`;
    const line = await talk(pipe, {
      hook_event_name: "PermissionRequest",
      session_id: sessionIdOf(req?.agent ?? current),
      coucou_agent: AGENT,
      tool_name: "user-questions",
      tool_input: { questions },
      request_id: requestId,
    }, DECISION_MS);
    if (!line || line === "deny") return next();
    let parsed;
    try {
      parsed = JSON.parse(line);
    } catch {
      return next();
    }
    const raw = parsed?.answers;
    if (!raw || typeof raw !== "object") return next();
    const answers = questions.map((question) => {
      // The island keys an answer by the question's id, or by its text when the
      // asker gave no id (views.ts). Read both, or a question without an id
      // would be silently unanswered.
      const key = typeof question?.id === "string" && question.id ? question.id : question?.question;
      const value = key == null ? undefined : raw[key];
      const selected = Array.isArray(value) ? value.map(String) : value ? [String(value)] : [];
      return { id: question?.id, selected };
    }).filter((item) => item.selected.length > 0);
    if (answers.length === 0) return next();
    return { answers };
  });

  if (steerPipe) {
    const server = net.createServer((socket) => {
      let buf = "";
      socket.on("data", (chunk) => {
        buf += chunk.toString("utf8");
        let nl;
        while ((nl = buf.indexOf("\n")) >= 0) {
          const line = buf.slice(0, nl);
          buf = buf.slice(nl + 1);
          void steerLine(line);
        }
      });
      socket.on("error", () => {});
    });
    server.on("error", () => {});
    try {
      server.listen(steerPipe);
    } catch {
      // Coucou keeps working; the island falls back to its own chat.
    }
    ctx.effect(() => () => {
      server.close();
    });
  }

  async function steerLine(line) {
    let msg;
    try {
      msg = JSON.parse(line);
    } catch {
      return;
    }
    if (!current) return;
    const kind = typeof msg.kind === "string" ? msg.kind : "steer";

    // Stop the turn that is running. `user` is the honest cause: a human asked.
    if (kind === "cancel") {
      try {
        current.cancel({ kind: "user" });
      } catch {
        // A dead session is not an error the island should surface.
      }
      return;
    }

    // Switch the session's permission preset.
    if (kind === "preset") {
      const presetName = typeof msg.preset === "string" ? msg.preset.trim() : "";
      if (presetName && presetsService && current?.session) {
        try {
          presetsService.set(current.session, presetName);
          sendPreset(current.session);
        } catch {
          // Preset unknown or invalid.
        }
      }
      return;
    }

    const text = typeof msg.text === "string" ? msg.text : "";
    if (!text.trim()) return;
    const message = await userMessage(text);
    try {
      if (typeof current.steer === "function") current.steer(message);
    } catch {
      // A dead session is not an error the island should surface.
    }
  }
}
