// Coucou plugin for DeepSeek Harness — generated by Coucou.
// Display events are fire-and-forget. Approval and questions wait for a click
// in the island, and hand the request to the Web GUI (next()) if Coucou is
// closed or nobody clicks. Nothing here allows a tool without that click.

import net from "node:net";
import module from "node:module";
import { pathToFileURL } from "node:url";

export const name = "coucou";

const AGENT = "dsh";
const CONNECT_MS = 400;
const DECISION_MS = 110_000;

function textOf(content) {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content
    .filter((block) => block && (block.type === "text" || block.type === undefined) && typeof block.text === "string")
    .map((block) => block.text)
    .join("\n");
}

function sessionIdOf(agent) {
  const id = agent?.id ?? agent?.session?.id ?? agent?.session?.header?.id ?? "";
  return typeof id === "string" ? id : String(id ?? "");
}

function findCreateUserMessage() {
  const keys = Object.keys(module._cache ?? {});
  const hit = keys.find((key) => key.replaceAll("\\", "/").includes("/@deepseek-ai/dsh-llm/"));
  if (!hit) return null;
  return import(pathToFileURL(hit).href)
    .then((mod) => mod.createUserMessage ?? null)
    .catch(() => null);
}

let createUserMessagePromise;

function userMessage(text) {
  if (!createUserMessagePromise) createUserMessagePromise = findCreateUserMessage();
  return createUserMessagePromise.then((create) => {
    if (typeof create === "function") {
      return create({
        content: [{ type: "text", text }],
        source: { kind: "user" },
      });
    }
    return {
      role: "user",
      id: `coucou-${Date.now()}`,
      content: [{ type: "text", text }],
      source: { kind: "user" },
    };
  });
}

function talk(pipe, payload, waitMs) {
  return new Promise((resolve) => {
    if (!pipe) {
      resolve(null);
      return;
    }
    let settled = false;
    const done = (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(value);
    };
    const socket = net.connect(pipe);
    let buf = "";
    const timer = setTimeout(() => {
      socket.destroy();
      done(null);
    }, waitMs);
    socket.on("connect", () => {
      socket.write(`${JSON.stringify(payload)}\n`);
      if (waitMs <= CONNECT_MS) {
        socket.end();
        done(null);
      }
    });
    socket.on("data", (chunk) => {
      buf += chunk.toString("utf8");
      const nl = buf.indexOf("\n");
      if (nl >= 0) {
        const line = buf.slice(0, nl).trim();
        socket.end();
        done(line);
      }
    });
    socket.on("error", () => done(null));
    socket.on("end", () => {
      if (waitMs > CONNECT_MS && !settled) done(buf.trim() || null);
    });
  });
}

function display(pipe, payload) {
  void talk(pipe, payload, CONNECT_MS);
}

export function apply(ctx, config) {
  const pipe = typeof config?.pipe === "string" ? config.pipe : "";
  const steerPipe = typeof config?.steerPipe === "string" ? config.steerPipe : "";
  const calls = new Map();
  const lastAssistant = new Map();
  let current = null;

  const remember = (agent) => {
    if (!agent || agent.origin === "subagent") return;
    current = agent;
  };

  ctx.on("agent/created", ({ agent }) => {
    remember(agent);
    const sid = sessionIdOf(agent);
    display(pipe, {
      hook_event_name: "SessionStart",
      session_id: sid,
      coucou_agent: AGENT,
      cwd: agent?.session?.header?.cwd ?? agent?.cwd ?? "",
    });
  });

  ctx.on("agent/disposed", ({ agent }) => {
    const sid = sessionIdOf(agent);
    if (current && sessionIdOf(current) === sid) current = null;
    display(pipe, {
      hook_event_name: "SessionEnd",
      session_id: sid,
      coucou_agent: AGENT,
    });
  });

  ctx.on("agent/pre-step", (payload, next) => {
    remember(payload?.agent);
    const text = (payload?.messages ?? []).map((message) => textOf(message?.content)).filter(Boolean).join("\n");
    if (text.trim()) {
      display(pipe, {
        hook_event_name: "UserPromptSubmit",
        session_id: sessionIdOf(payload.agent),
        coucou_agent: AGENT,
        prompt: text,
      });
    }
    return next();
  });

  ctx.on("session/event", (session, event) => {
    if (event?.type !== "assistant/message") return;
    const text = textOf(event.data?.message?.content ?? event.data?.content);
    if (text.trim()) lastAssistant.set(session?.id ?? sessionIdOf(session), text);
  });

  ctx.on("tools/pre-execute", (exec, next) => {
    const callId = exec?.callId ? String(exec.callId) : "";
    if (callId) calls.set(callId, { name: exec.name, arguments: exec.arguments ?? {} });
    display(pipe, {
      hook_event_name: "PreToolUse",
      session_id: sessionIdOf(exec?.agent),
      coucou_agent: AGENT,
      tool_name: exec?.name ?? "",
      tool_input: exec?.arguments ?? {},
    });
    // Display only. Never deny or ask from this path.
    return next();
  });

  ctx.on("tools/post-execute", (exec, result, next) => {
    const cached = calls.get(String(exec?.callId ?? ""));
    display(pipe, {
      hook_event_name: "PostToolUse",
      session_id: sessionIdOf(exec?.agent),
      coucou_agent: AGENT,
      tool_name: exec?.name ?? "",
      tool_input: cached?.arguments ?? exec?.arguments ?? {},
      tool_response: result?.isError ? { error: true } : undefined,
    });
    return next();
  });

  ctx.on("agent/turn-stopping", (payload) => {
    const sid = sessionIdOf(payload?.agent);
    const text = lastAssistant.get(sid) ?? "";
    display(pipe, {
      hook_event_name: "Stop",
      session_id: sid,
      coucou_agent: AGENT,
      last_assistant_message: text,
    });
  });

  ctx.on("subagent/start", (info) => {
    display(pipe, {
      hook_event_name: "SubagentStart",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: info?.provider ? `+ ${info.provider}` : "+ subagent",
    });
  });

  ctx.on("subagent/end", (info) => {
    display(pipe, {
      hook_event_name: "SubagentStop",
      session_id: sessionIdOf(current),
      coucou_agent: AGENT,
      message: "• subagent done",
    });
    const text = textOf(info?.lastAssistantMessage);
    if (text.trim() && info?.id) lastAssistant.set(String(info.id), text);
  });

  ctx.on("approval/request", async (req, next) => {
    const callId = req?.callId ? String(req.callId) : "";
    const cached = callId ? calls.get(callId) : undefined;
    const tool = req?.toolName || cached?.name || "tool";
    const input = cached?.arguments ?? {};
    const line = await talk(pipe, {
      hook_event_name: "PermissionRequest",
      session_id: sessionIdOf(req?.agent ?? current),
      coucou_agent: AGENT,
      tool_name: tool,
      tool_input: input,
      request_id: callId || `dsh-${Date.now()}`,
    }, DECISION_MS);
    if (line === "allow") return "allowed-once";
    if (line === "deny") return "rejected";
    return next();
  });

  ctx.on("user-questions/request", async (req, next) => {
    const questions = Array.isArray(req?.questions) ? req.questions : [];
    if (questions.length === 0) return next();
    const requestId = `dsh-q-${Date.now()}`;
    const line = await talk(pipe, {
      hook_event_name: "PermissionRequest",
      session_id: sessionIdOf(req?.agent ?? current),
      coucou_agent: AGENT,
      tool_name: "user-questions",
      tool_input: { questions },
      request_id: requestId,
    }, DECISION_MS);
    if (!line || line === "deny") return next();
    let parsed;
    try {
      parsed = JSON.parse(line);
    } catch {
      return next();
    }
    const raw = parsed?.answers;
    if (!raw || typeof raw !== "object") return next();
    const answers = questions.map((question) => {
      const value = raw[question.id];
      const selected = Array.isArray(value) ? value.map(String) : value ? [String(value)] : [];
      return { id: question.id, selected };
    }).filter((item) => item.selected.length > 0);
    if (answers.length === 0) return next();
    return { answers };
  });

  if (steerPipe) {
    const server = net.createServer((socket) => {
      let buf = "";
      socket.on("data", (chunk) => {
        buf += chunk.toString("utf8");
        let nl;
        while ((nl = buf.indexOf("\n")) >= 0) {
          const line = buf.slice(0, nl);
          buf = buf.slice(nl + 1);
          void steerLine(line);
        }
      });
      socket.on("error", () => {});
    });
    server.on("error", () => {});
    try {
      server.listen(steerPipe);
    } catch {
      // Coucou keeps working; the island falls back to its own chat.
    }
    ctx.effect(() => () => {
      server.close();
    });
  }

  async function steerLine(line) {
    let msg;
    try {
      msg = JSON.parse(line);
    } catch {
      return;
    }
    const text = typeof msg.text === "string" ? msg.text : "";
    if (!text.trim() || !current || typeof current.steer !== "function") return;
    const message = await userMessage(text);
    try {
      current.steer(message);
    } catch {
      // A dead session is not an error the island should surface.
    }
  }
}
